server:
  port: 8081
spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password: yyhwy
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 500
        min-idle: 0
    lettuce:
      shutdown-timeout: 0
  datasource:
    url: jdbc:mysql://localhost:3306/bwl?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource

#mybatis:
#  type-aliases-package: com.neo.model

sms:
  key: d41d8cd98f00b204e980
  uid: yangalan
  ip: http://utf8.api.smschinese.cn/?Uid={uid}&Key={key}&smsMob={smsMob}&smsText={smsText}



